service_id_name = "partner-sandbox-admin-id"
region = "us-south"
sat_access_group_name = "TEST-SAT-ADMIN"
users_access_group_name = "TEST-USER"
admins_access_group_name = "TEST-ADMIN"
serviceid_access_group_name = "TEST-SERVICEID"
resource_group_name = "test"
